import type { Course } from "@/types/course";

export const dummyCourses: Course[] = [
  {
    id: "1",
    title: "Next.js for Beginners",
    description: "Learn the fundamentals of Next.js and build modern web applications.",
    longDescription: "This course covers Next.js basics, including routing, data fetching, API routes, and deployment. Perfect for those new to React frameworks or looking to master server-side rendering and static site generation with Next.js.",
    category: "Web Development",
    skillLevel: "Beginner",
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "web development",
    instructor: "Jane Doe",
    duration: "12 hours",
    tags: ["Next.js", "React", "JavaScript"],
    rating: 4.5,
    enrollmentCount: 1250,
    lessons: [
      { id: "l1-1", title: "Introduction to Next.js", videoId: "fmvS0s3r3fA", duration: "15 min", description: "Overview of Next.js features and benefits." },
      { id: "l1-2", title: "Setting up your environment", videoId: "ZEROPS02lkc", duration: "25 min", description: "Installation and project setup." },
      { id: "l1-3", title: "Pages and Routing", videoId: "nxtW9cSKDXo", duration: "45 min", description: "Learn about file-system routing and dynamic routes." },
    ],
  },
  {
    id: "2",
    title: "Advanced Python for Data Science",
    description: "Dive deep into Python programming for complex data analysis and machine learning.",
    longDescription: "Master advanced Python concepts, libraries like NumPy, Pandas, and Scikit-learn, and apply them to real-world data science problems. Includes projects on data visualization and model building.",
    category: "Data Science",
    skillLevel: "Advanced",
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "data science",
    instructor: "John Smith",
    duration: "20 hours",
    tags: ["Python", "Data Analysis", "Machine Learning"],
    rating: 4.8,
    enrollmentCount: 870,
    lessons: [
      { id: "l2-1", title: "Advanced Pandas Techniques", videoId: "vmEHCJofslg", duration: "60 min" },
      { id: "l2-2", title: "NumPy for High Performance", videoId: "r-ZV-3aF3jI", duration: "50 min" },
    ],
  },
  {
    id: "3",
    title: "iOS App Development with Swift",
    description: "Build beautiful and functional iOS applications using Swift and Xcode.",
    longDescription: "From UI design with SwiftUI to Core Data and API integration, this course guides you through building complete iOS apps. Suitable for aspiring mobile developers.",
    category: "Mobile Apps",
    skillLevel: "Intermediate",
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "mobile development",
    instructor: "Alice Brown",
    duration: "25 hours",
    tags: ["iOS", "Swift", "Mobile Development"],
    rating: 4.7,
    enrollmentCount: 980,
    lessons: [
      { id: "l3-1", title: "Introduction to SwiftUI", videoId: "b14pT032A0A", duration: "40 min" },
    ],
  },
  {
    id: "4",
    title: "Cybersecurity Essentials",
    description: "Understand the core principles of cybersecurity and protect digital assets.",
    longDescription: "Learn about common threats, vulnerabilities, network security, cryptography, and ethical hacking. A foundational course for anyone interested in cybersecurity.",
    category: "Cybersecurity",
    skillLevel: "Beginner",
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "cybersecurity",
    instructor: "Michael Green",
    duration: "15 hours",
    tags: ["Security", "Networking", "Ethical Hacking"],
    rating: 4.6,
    enrollmentCount: 1500,
  },
  {
    id: "5",
    title: "Introduction to Machine Learning",
    description: "Grasp the fundamentals of machine learning algorithms and concepts.",
    longDescription: "Explore supervised and unsupervised learning, model evaluation, and popular algorithms like decision trees and neural networks. Hands-on exercises with Python.",
    category: "AI & ML",
    skillLevel: "Intermediate",
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "machine learning",
    instructor: "Sophia White",
    duration: "18 hours",
    tags: ["AI", "Machine Learning", "Python"],
    rating: 4.9,
    enrollmentCount: 2200,
  },
  {
    id: "6",
    title: "Full-Stack Web Development Bootcamp",
    description: "Become a full-stack developer by learning front-end and back-end technologies.",
    longDescription: "Covers HTML, CSS, JavaScript, React, Node.js, Express, and databases. Build multiple projects and develop a strong portfolio. Intensive and comprehensive.",
    category: "Web Development",
    skillLevel: "Intermediate",
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "web development code",
    instructor: "David Lee",
    duration: "40 hours",
    tags: ["HTML", "CSS", "JavaScript", "React", "Node.js"],
    rating: 4.7,
    enrollmentCount: 1800,
  },
   {
    id: "7",
    title: "Unity Game Development Basics",
    description: "Learn to create your first 2D and 3D games using the Unity engine and C#.",
    longDescription: "This beginner-friendly course introduces the Unity interface, game objects, scripting with C#, physics, UI, and animation. By the end, you'll build a few small games.",
    category: "Game Development",
    skillLevel: "Beginner",
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "game development",
    instructor: "Chris Taylor",
    duration: "22 hours",
    tags: ["Unity", "C#", "Game Design"],
    rating: 4.6,
    enrollmentCount: 750,
  }
];
